openapi: 3.0.1
info:
  title: Simulacao Credito Creditas
  description: Simulação de empréstimos
  version: 1.0.0
paths:
  /simulacao/credito:
    get:
      summary: Calcular uma simulação de um empréstimo para o cliente
      operationId: getSimulacaoEmprestimo
      tags:
        - Simulacao Credito
      parameters:
        - $ref: '#/components/parameters/valorEmprestimo'
        - $ref: '#/components/parameters/dataNascimento'
        - $ref: '#/components/parameters/parcelas'
      responses:
        200:
          description: sucesso
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SimulacaoEmprestimoResponse'


components:
  parameters:
    valorEmprestimo:
      in: query
      name: valorEmprestimo
      required: true
      schema:
        type: number

    dataNascimento:
      in: query
      name: dataNascimento
      required: true
      schema:
        type: string
        format: date

    parcelas:
      in: query
      name: qtdParcelas
      required: true
      schema:
        type: integer

  schemas:
    SimulacaoEmprestimoResponse:
      type: object
      properties:
        valorTotal:
          type: number
          example: 100.0
        valorParcelas:
          type: number
          example: 10.1
        totalJuros:
          type: number
          example: 101.0
        dataSimulacao:
          type: string
          example: 2025-01-07
